---
title: "3_stan"
output: html_document
---

```{r}
library(tidyverse)
library(rstan)
library(tidybayes)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
source("R/stan.R")

pars <- read_rds("data-simulated/1_pars.rds") %>% mutate(item = row_number())
results <- read_rds("data-simulated/1_results.rds")
```

# fit model

```{r}
stan_data <- 
    results %>% 
    select(-item_10) %>% 
    select(starts_with("item")) %>% 
    irt_data_wide_to_long() %>% 
    irt_data_long_to_stan_list()

stan_model <- 
    stan(
        file = "stan/2pl.stan",
        data = stan_data,
        seed = 1,
        chains = 4,
        iter = 2000,
        save_dso = TRUE
    )

get_variables(stan_model)
```

# look at items

```{r}
items <- 
    stan_model %>% 
    recover_types() %>% 
    spread_draws(alpha[item], beta[item])

items %>% 
    ggplot(aes(x = alpha)) +
    geom_histogram() +
    facet_wrap(~ item, scales = "free") +
    geom_vline(data = pars, aes(xintercept = a1), color = "blue")

items %>% 
    summarize(alpha = mean(alpha), beta = mean(beta)) %>% 
    left_join(pars)
```

# look at students

```{r}

```

# save

