---
title: "4_comparison"
output: github_document
---

```{r}
# load("4_comparison.Rdata")
# save.image("4_comparison.Rdata")
library(mirt)
library(tidyverse)
library(rstan)
library(tidybayes)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
source("R/stan.R")
```

# simulate data
[alpha ~ lognormal(0, 1); beta ~ normal(2, 1); theta ~ normal(0, 1)]

```{r}
set.seed(1)
n_items <- 8
n_students <- 1000
    
dim <- 1

pars <-
    tibble(
        item = 1:n_items,
        a1 = rlnorm(n_items * dim, 0, 1),
        d = rnorm(n_items, 2, 1)
    )

sim <- 
    simdata(
        a = matrix(pars$a1, nrow = n_items, ncol = dim),
        d = matrix(pars$d, ncol = 1),
        guess = rep(0, n_items),
        N = n_students,
        mu = 0,
        sigma = diag(dim),
        itemtype = rep("3PL", n_items),
        returnList = TRUE
    )
```

# models

1. marginal maximum likelihood estimation 
[theta ~ normal(0, 1)]

```{r}
mmle <- mirt(sim$data, 1, "2PL")

mmle_items <- 
    coef(mmle, simplify = TRUE)$items %>% 
    as_tibble() %>% 
    mutate(item = row_number(), model = "mmle") %>% 
    select(item, alpha = a1, beta = d, model)

mmle_persons <- 
    tibble(
        person = 1:n_students,
        theta = fscores(mmle, method = "EAP")[ , 1],
        model = "mmle"
    )
```

2. marginal bayesian likelihood estimation 
[alpha ~ lognormal(0, 2); beta ~ normal(0, 2); theta ~ normal(0, 1)]

```{r}
mble_spec <-
    str_glue(
        "F = 1-{n_items}
        PRIOR = (1-{n_items}, a1, lnorm, 0, 2),(1-{n_items}, d, norm, 0, 2)"
    )

mble <- mirt(sim$data, mirt.model(mble_spec))

mble_items <- 
    coef(mble, simplify = TRUE)$items %>% 
    as_tibble() %>% 
    mutate(item = row_number(), model = "mble") %>% 
    select(item, alpha = a1, beta = d, model)

mble_persons <- 
    tibble(
        person = 1:n_students,
        theta = fscores(mble, method = "EAP")[ , 1],
        model = "mble"
    )
```

3. mcmc 
[alpha ~ lognormal(0, 2); beta ~ normal(0, 2); theta ~ normal(0, 1)]

```{r}
mcmc <- 
    stan(
        file = "stan/2pl.stan",
        data = 
            sim$data %>% 
            as_tibble() %>% 
            irt_data_wide_to_long() %>% 
            irt_data_long_to_stan_list(),
        seed = 1,
        chains = 4,
        iter = 2000,
        save_dso = TRUE,
        # control = list(adapt_delta = 0.99)
    )

get_variables(mcmc)[1:40]

traceplot(mcmc, pars = "beta")

plot(mcmc, pars = "beta")

mcmc_item_draws <- 
    mcmc %>% 
    spread_draws(alpha[item], beta[item])

mcmc_items <- 
    mcmc_item_draws %>% 
    summarize(alpha = mean(alpha), beta = mean(beta)) %>% 
    mutate(model = "mcmc")

mcmc_person_draws <- 
    mcmc %>% 
    spread_draws(theta[person])

mcmc_persons <- 
    mcmc_person_draws %>% 
    summarize(theta = mean(theta)) %>% 
    mutate(model = "mcmc")
```

# items

```{r}
all_items <- 
    pars %>% 
    rename(alpha = a1, beta = d) %>% 
    mutate(model = "true") %>% 
    bind_rows(
        mmle_items,
        mble_items,
        mcmc_items
    ) %>% 
    gather(parameter, value, alpha, beta)

all_items %>% spread(model, value)

mcmc_item_draws %>% 
    gather(parameter, value, alpha, beta) %>% 
    ggplot(aes(x = value)) +
    geom_histogram() +
    facet_grid(item ~ parameter, scales = "free") +
    geom_vline(data = all_items, aes(xintercept = value, color = model))
```

# persons

```{r}
all_persons <- 
    tibble(
        person = 1:n_students,
        theta = sim$Theta[ , 1],
        model = "true"
    ) %>% 
    bind_rows(
        mmle_persons,
        mble_persons,
        mcmc_persons
    )
    
all_persons %>% 
    spread(model, theta) %>% 
    select(-person) %>% 
    GGally::ggpairs()
```
