---
title: "4_comparison"
output: github_document
---

```{r}
# load("4_comparison.Rdata")
# save.image("4_comparison.Rdata")
library(mirt)
library(tidyverse)
library(rstan)
library(tidybayes)
library(brms)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
source("R/stan.R")
```

# simulate data
[theta ~ normal(0, 1)]

```{r}
set.seed(1)
n_items <- 8
n_students <- 5000
dim <- 1

pars <-
    tibble(
        item = 1:n_items,
        alpha = rep(seq(0.5, 2, 0.5), 2),
        beta = seq(-1.5, 2, 0.5)
    )

sim <- 
    simdata(
        a = matrix(pars$alpha, nrow = n_items, ncol = dim),
        d = matrix(pars$beta, ncol = 1),
        guess = rep(0, n_items),
        N = n_students,
        mu = 0,
        sigma = diag(dim),
        itemtype = rep("3PL", n_items),
        returnList = TRUE
    )
```

# models

## 1. marginal maximum likelihood estimation 
[theta ~ normal(0, 1)]

```{r}
# fit
mmle <- mirt(sim$data, 1, "2PL")

# summarize
mmle_items <- 
    coef(mmle, simplify = TRUE)$items %>% 
    as_tibble() %>% 
    mutate(item = row_number(), model = "mmle") %>% 
    select(item, alpha = a1, beta = d, model)

mmle_persons <- 
    tibble(
        person = 1:n_students,
        theta = fscores(mmle, method = "EAP")[ , 1],
        model = "mmle"
    )
```

## 2. marginal bayesian likelihood estimation 
[alpha ~ lognormal(0, 2); beta ~ normal(0, 2); theta ~ normal(0, 1)]

```{r}
# fit
mble_spec <-
    str_glue(
        "F = 1-{n_items}
        PRIOR = (1-{n_items}, a1, lnorm, 0, 2),(1-{n_items}, d, norm, 0, 2)"
    )

mble <- mirt(sim$data, mirt.model(mble_spec))

# summarize
mble_items <- 
    coef(mble, simplify = TRUE)$items %>% 
    as_tibble() %>% 
    mutate(item = row_number(), model = "mble") %>% 
    select(item, alpha = a1, beta = d, model)

mble_persons <- 
    tibble(
        person = 1:n_students,
        theta = fscores(mble, method = "EAP")[ , 1],
        model = "mble"
    )
```

## 3. mcmc 
[alpha ~ lognormal(0, 2); beta ~ normal(0, 2); theta ~ normal(0, 1)]

```{r}
# fit
mcmc <- 
    stan(
        file = "stan/2pl.stan",
        data = 
            sim$data %>% 
            as_tibble() %>% 
            irt_data_wide_to_long() %>% 
            irt_data_long_to_stan_list(),
        seed = 1,
        chains = 4,
        iter = 4000,
        save_dso = TRUE,
        control = list(adapt_delta = 0.9)
    )

# peek
get_variables(mcmc)[1:40]
traceplot(mcmc, pars = "beta")
plot(mcmc, pars = "alpha")
plot(mcmc, pars = "beta")

# summarize
mcmc_item_draws <- 
    mcmc %>% 
    spread_draws(alpha[item], beta[item])

mcmc_items <- 
    mcmc_item_draws %>% 
    summarize(alpha = mean(alpha), beta = mean(beta)) %>% 
    mutate(model = "mcmc")

mcmc_person_draws <- 
    mcmc %>% 
    spread_draws(theta[person])

mcmc_persons <- 
    mcmc_person_draws %>% 
    summarize(theta = mean(theta)) %>% 
    mutate(model = "mcmc")
```

## 4. mcmc pooled items
[alpha ~ lognormal(0, 2); beta ~ normal(mu_beta, sigma_beta); theta ~ normal(0, 1)]
[mu_beta ~ normal(0, 3), sigma_beta ~ normal(1, 3)]

```{r}
# fit 
mcmc_pooled_items <- 
    stan(
        file = "stan/2pl_pooled_items.stan",
        data = 
            sim$data %>% 
            as_tibble() %>% 
            irt_data_wide_to_long() %>% 
            irt_data_long_to_stan_list(),
        seed = 1,
        chains = 4,
        iter = 4000,
        save_dso = TRUE,
        control = list(adapt_delta = 0.9)
    )

# peek
get_variables(mcmc_pooled_items)[1:40]
traceplot(mcmc_pooled_items, pars = "beta")
plot(mcmc_pooled_items, pars = "mu_beta")
plot(mcmc_pooled_items, pars = "sd_beta")
plot(mcmc_pooled_items, pars = "alpha")
plot(mcmc_pooled_items, pars = "beta")

# summarize
mcmc_pooled_items_item_draws <- 
    mcmc_pooled_items %>% 
    spread_draws(alpha[item], beta[item])

mcmc_pooled_items_items <- 
    mcmc_pooled_items_item_draws %>% 
    summarize(alpha = mean(alpha), beta = mean(beta)) %>% 
    mutate(model = "mcmc_pooled_items")

mcmc_pooled_items_person_draws <- 
    mcmc %>% 
    spread_draws(theta[person])

mcmc_pooled_items_persons <- 
    mcmc_pooled_items_person_draws %>% 
    summarize(theta = mean(theta)) %>% 
    mutate(model = "mcmc_pooled_items")
```

## 5. brms

```{r}
# wrangle
brms_data <- 
    sim$data %>% 
    as_tibble() %>% 
    irt_data_wide_to_long() %>% 
    mutate_all(as.factor)

# fit
formula_2pl <- 
    bf(
        correct ~ exp(logalpha) * eta,
        eta ~ 1 + (1 | person) + (1 |i| item),
        logalpha ~ 1 + (1 |i| item),
        nl = TRUE
    )

prior_2pl <- 
    prior("normal(0, 5)", class = "b", nlpar = "eta") + 
    prior("normal(0, 3)", class = "sd", nlpar = "eta", group = "person") + 
    prior("normal(0, 3)", class = "sd", nlpar = "eta", group = "item") +
    prior("normal(0, 1)", class = "b", nlpar = "logalpha") + 
    prior("normal(0, 1)", class = "sd", nlpar = "logalpha", group = "item")

brms_model <- 
    brm(
        data = brms_data,
        formula = formula_2pl,
        family = brmsfamily("bernoulli", "logit"),
        prior = prior_2pl,
        inits = 0,
        chains = 4,
        iter = 4000,
    )

# peek
get_variables(brms_model)[1:40]

posterior_samples(brms_model, "cor_item__eta_Intercept__logalpha_Intercept") %>% 
    as_tibble() %>% 
    select(x = 1) %>% 
    ggplot(aes(x)) +
    geom_histogram()

posterior_samples(brms_model, "r_item__logalpha") %>% 
    as_tibble() %>% 
    set_names(paste0("logalpha", 1:8))
```

# items

```{r}
all_items <- 
    pars %>% 
    mutate(model = "true") %>% 
    bind_rows(
        mmle_items,
        mble_items,
        mcmc_items,
        mcmc_pooled_items_items
    ) %>% 
    gather(parameter, value, alpha, beta) 

all_items %>% spread(model, value)

all_items %>% 
    ggplot(aes(x = item, y = value, color = model)) +
    geom_point() +
    facet_wrap(~ parameter)

bind_rows(
    mcmc_item_draws %>% mutate(model = "mcmc"),
    mcmc_pooled_items_item_draws %>% mutate(model = "mcmc_pooled")
) %>% 
    ungroup() %>% 
    select(item, alpha, beta, model) %>% 
    gather(parameter, value, -item, -model) %>% 
    filter(item == 4, parameter == "alpha") %>% 
    ggplot(aes(x = value)) +
    geom_histogram() +
    facet_wrap(~ model, ncol = 1) +
    geom_vline(xintercept = pars$alpha[4], color = "green") +
    geom_vline(xintercept = mmle_items$alpha[4], color = "blue") +
    geom_vline(xintercept = mble_items$alpha[4], color = "red")
```

# persons

```{r}
all_persons <- 
    tibble(
        person = 1:n_students,
        theta = sim$Theta[ , 1],
        model = "true"
    ) %>% 
    bind_rows(
        mmle_persons,
        mble_persons,
        mcmc_persons,
        mcmc_pooled_items_persons
    )
    
all_persons %>% 
    spread(model, theta) %>% 
    select(-person) %>% 
    GGally::ggpairs()
```

# look across

```{r}
mcmc %>% 
    spread_draws(alpha[item]) %>% 
    ungroup() %>% 
    filter(item == 1) %>% 
    select(.draw, alpha) %>% 
    left_join(
        mcmc %>% 
            spread_draws(theta[person]) %>% 
            ungroup() %>% 
            filter(person == 1) %>% 
            select(.draw, theta)
    ) %>% 
    ggplot(aes(x = alpha, y = theta)) +
    geom_point(alpha = 0.1) +
    geom_smooth(se = FALSE, method = "lm")

mcmc %>% 
    spread_draws(beta[item]) %>% 
    ungroup() %>% 
    filter(item == 1) %>% 
    select(.draw, beta) %>% 
    left_join(
        mcmc %>% 
    spread_draws(beta[item]) %>% 
    ungroup() %>% 
    filter(item == 4) %>% 
    select(.draw, beta1 = beta)
    ) %>% 
    ggplot(aes(x = beta, y = beta1)) +
    geom_point(alpha = 0.1) +
    geom_smooth(se = FALSE, method = "lm")
```

