---
title: "6_order_effects"
output: github_document
---

```{r}
# load("3_stan_first9.Rdata")
# save.image("3_stan_first9.Rdata")
library(tidyverse)
library(rstan)
library(tidybayes)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
source("R/stan.R")

pars <- read_rds("data-simulated/1_pars_rasch.rds")

results <- read_rds("data-simulated/1_results_rasch.rds")

stan_data <- 
    results %>% 
    select(starts_with("item")) %>% 
    irt_data_wide_to_long() %>% 
    irt_data_long_to_stan_list()

stan_data$last <- 
    tibble(
        ii = stan_data$ii,
        jj = stan_data$jj,
        y = stan_data$y    
    ) %>% 
    arrange(jj, ii) %>% 
    group_by(jj) %>% 
    mutate(last = lag(y) %>% replace_na(0)) %>% 
    ungroup() %>% 
    pull(last)

pars

results$theta_1to9 %>% mean()

results %>% 
    group_by(item_9) %>% 
    summarize(mean(item_10))
```

fit the model

```{r}
model <- 
    stan(
        file = "stan/2pl_order_effects_rasch.stan",
        data = stan_data,
        seed = 1,
        chains = 4,
        iter = 1000,
        save_dso = TRUE,
        control = list(adapt_delta = 0.9)
    )



get_variables(model)[1:40]
plot(model, pars = "beta")
plot(model, pars = "theta")
plot(model, pars = "boost")
traceplot(model, pars = "boost")
```

```{r}
p <- model %>% spread_draws(theta[person])
out <- p %>% summarize(t = mean(theta))

results %>% 
    select(item_9, theta_1to9) %>% 
    mutate(est = out$t) %>% 
    group_by(item_9) %>% 
    summarize(mean(est - theta_1to9))
    
    
    ggplot(aes(x = theta_1to9, y = est, color = item_9)) +
    geom_point()
```

